export const FETCH_ORDERS = 'FETCH_ORDERS';

export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';

export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';

export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';